services:
  pg:
    type: postgres
    engine_version: 16.0
    instance_type: t4g.nano
    volume_size: 25
  mysql:
    type: mysql
    engine_version: 8.1
    instance_type: t4g.nano
    volume_size: 30
  app:
    dockerfile: Dockerfile.production
    build_context: app
    command: rails s
    env:
      RAILS_MASTER_KEY:
        secret: master-key
      WEATHER: sunny
      RAILS_ENV: preview
      DATABASE_URL:
        service: pg
        key: url
    instance_type: t4g.small
    health_check: /up
  blog:
    image: wordpress
    env:
      DATABASE_HOST:
        service: mysql
        key: host
      DATABASE_NAME:
        service: mysql
        key: name
    volume_mount: /usr/public/html
    volume_size: 30
    private: true

environments:
  production:
    pg:
      instance_type: t4g.large
      volume_size: 400
    mysql:
      instance_type: t4g.2xlarge
      volume_size: 500
    app:
      dockerfile: Dockerfile.production
      build_context: app
      env:
        WEATHER: null
        RAILS_ENV: production
        RAILS_MAX_THREADS: 5
      instance_type: t4g.medium
      min_instances: 2
      max_instances: 4
